#!/usr/bin/env python

import redis
import json
import sys
from datetime import datetime

r = redis.StrictRedis(host="localhost")

# object with static stuff
obj = {
        "@fields": {},
        "@type": "testing",
        "@tags": ["tag1", "tag2"],
}

for line in sys.stdin:
    obj["@timestamp"] = datetime.utcnow().isoformat('T') + 'Z'
    line = line.rstrip()
    obj["@message"] = line
    r.rpush("logstash", json.dumps(obj))
    print json.dumps(obj)
